### ISSUE TITLE
Migrate OAuth Client ID to the correct GCP project

### ISSUE THREAD

**Issue by evonide** [google/vulncode-db#29]
The OAuth Client ID / consent screen is currently configured under `google.com:ruslanh-vulncodedb`.
Instead, it should be running fully under `vulncode-db`.

**Comment by we08guyy** [comment]
Agree. Otherwise I cannot login locally and cannot use admin_required functions.

**Comment by evonide** [comment]
Thanks for your comment we08guyy!
Logging in locally should actually be possible now independent of the described issue.
I've explicitly added http://localhost:8080 and http://127.0.0.1:8080 as valid OAuth login origins.

The only thing you should be required to do is to replace the "user@gmail.com" account with your own Gmail account at the bottom of the app.yaml as can be seen in the [example_app.yaml](https://github.com/google/vulncode-db/blob/master/example_app.yaml), too.

Please let me know if that doesn't work or you need any assistance.

**Comment by we08guyy** [comment]
Thanks for helping~ But the Google's login page just says "Missing required parameter: client_id".

**Comment by evonide** [comment]
I realized my answer above is incomplete. To make this work you actually have to provide a correct OAuth consumer key and secret in the app.yaml in addition:
> OAUTH_CONSUMER_KEY: ''
> OAUTH_CONSUMER_SECRET: ''

The one the application on vulncode-db.com is using is not shared in the repository.

I'll add a simplified login screen which will allow to select one of the app.yaml admin accounts and bypass OAuth for the local development environment completely. I'll update this thread once this is done.

**Comment by evonide** [comment]
I've just addressed this with https://github.com/google/vulncode-db/commit/4ba82da9221c94a59c912706eda71ac3c3ee1a80.

It should now be possible to select and login with any specified admin on the local dev environment bypassing OAuth. Please let me know if that doesn't work :).

**Comment by evonide** [comment]
Created new a new OAuth service account in the `vulncode-db` GCP project.
