### ISSUE TITLE
License for the added data at https://www.vulncode-db.com/ 

### ISSUE THREAD

**Issue by pombredanne** [google/vulncode-db#3]
Hi what would be the license for the data at https://www.vulncode-db.com/ ? is there a way to get that through some API too? 
I am asking as I would want to include your data in this project most likely https://nlnet.nl/project/vulnerabilitydatabase/ 
Thank you!

**Comment by armijnhemel** [comment]
I would want to second this. It would be great to have the data under a license that would encourage reuse.

**Comment by evonide** [comment]
Hi pombredanne and armijnhemel, thanks for your request!

Please consider that the project is using different data sources like NVD/CVE and code from Github which all have there own licenses. Reusing this data from https://www.vulncode-db.com/ would require to uphold such license agreements accordingly.

Any data that is exclusively provided through https://vulncode-db.com such as vulnerability annotations and the linking of vulnerabilities with their patches etc. will run under the same agreement as is provided by the Common Vulnerabilities and Exposures. To re-use it here:

> Vulncode-DB hereby grants you a perpetual, worldwide, non-exclusive,
> no-charge, royalty-free, irrevocable copyright license to reproduce, prepare
> derivative works of, publicly display, publicly perform, sublicense, and
> distribute data which is exclusively provided by Vulncode-DB. Any copy you make for
> such purposes is authorized provided that you reproduce Vulncode-DB's copyright
> designation and this license in any such copy.

I'll add this information in the next commits to the project's Readme file, too, to make this clear.

> Is there a way to get that through some API too?

An API is planned but currently does not exist. Please let us know if there is something specific you might need and we can see how we can accommodate you best.

> I am asking as I would want to include your data in this project most likely https://nlnet.nl/project/vulnerabilitydatabase/

That sounds exciting thanks for considering Vulncode-DB as a potential source for this :).
Please let me know if you have any more questions?

**Comment by pombredanne** [comment]
@evonide thanks you ++ for your quick and comprehensive reply
