### ISSUE TITLE
Move Python packages from third_party directory to virtual environment

### ISSUE THREAD

**Issue by evonide** [google/vulncode-db#33]
For historic reasons when running the application outside of Docker all Python dependencies were meant to be installed to the `third_party` directory as AppEngine required them to be shipped.

With the newest AppEngine version this is not required anymore. We should move any `third_party` dependencies to be installed inside a virtual environment instead and remove `third_party` directory mentions from the code.

**Comment by bluec0re** [comment]
Finalized in 9c35fd5
