### ISSUE TITLE
Update go-cve-dictionary submodule 

### ISSUE THREAD

**Issue by sbs2001** [google/vulncode-db#41]
Vulncode-db uses https://github.com/kotakanbe/go-cve-dictionary which is present as a git submodule. It uses https://github.com/kotakanbe/go-cve-dictionary/tree/5fe52611f0b8dff9f95374d9cd7bdb23cc5fc67a to be more specific which is 1+ year old version.  

https://github.com/kotakanbe/go-cve-dictionary/tree/5fe52611f0b8dff9f95374d9cd7bdb23cc5fc67a no longer works due to some changes. Here's the log :

```
Sending build context to Docker daemon  608.8kB
Step 1/16 : FROM golang:alpine as builder
 ---> 1a87ceb1ace5
Step 2/16 : RUN apk add --no-cache         git         make         gcc         musl-dev
 ---> Using cache
 ---> 90867a3f9751
Step 3/16 : ENV REPOSITORY github.com/kotakanbe/go-cve-dictionary
 ---> Using cache
 ---> 2fc568001ee8
Step 4/16 : COPY . $GOPATH/src/$REPOSITORY
 ---> 28d1be732cc6
Step 5/16 : RUN cd $GOPATH/src/$REPOSITORY && make install
 ---> Running in 24a0108db67c
go get -u github.com/golang/dep/...
dep ensure -v
# Gopkg.lock is out of sync with Gopkg.toml and project imports:
github.com/pkg/errors: imported or required, but missing from Gopkg.lock's input-imports
``` 
Due to this `./docker-admin.sh init` does not work too.

`./docker-admin.sh init` works alright after updating the `go-cve-dictionary` to their current master branch.
Please update `go-cve-dictionary`

**Comment by evonide** [comment]
Hi Shivam,

Thanks a lot for raising this! I've just tried to reproduce this but for me it seems to work:
```dep ensure -v
# Gopkg.lock is out of sync with Gopkg.toml and project imports:
github.com/pkg/errors: imported or required, but missing from Gopkg.lock's input-imports

Root project is "github.com/kotakanbe/go-cve-dictionary"
 13 transitively valid internal packages
 21 external packages imported from 15 projects
(0)   ✓ select (root)
(1)	? attempt github.com/asaskevich/govalidator with 1 pkgs; at least 1 versions to try
(1)	    try github.com/asaskevich/govalidator@v9
(1)	✓ select github.com/asaskevich/govalidator@v9 w/1 pkgs
(2)	? attempt github.com/cheggaaa/pb with 1 pkgs; at least 1 versions to try
[...]
```
as you can see Docker keeps building the container from the image successfully.

Having said that I want to update the `go-cve-dictionary` dependency in any case but it can lead to some other issues down the line in regard to an unexpected database layout. Particularly, the database layout provided by `go-cve-dictionary` needs to be consistent with the data Vulncode-DB expects. I'll investigate any potential mismatches and check how complex it would be to update this soon.

**Comment by sbs2001** [comment]
@evonide  thanks for the super fast reply. I tried the old version again and that's working fine, probably the issue was caused due to my network connection. So feel free to close this.

FWIW https://github.com/kotakanbe/go-cve-dictionary/blob/5fe52611f0b8dff9f95374d9cd7bdb23cc5fc67a/models/models.go hasn't been changed since  last 2 years so on the models side it should be fine. Atleast my  VulnCode-db fork with latest `go-cve-dictionary` worked fine, but again I am not done with exploring all the goodies :)

**Comment by evonide** [comment]
Fortunately, only minor changes were required to update this :).
This has now been resolved with https://github.com/google/vulncode-db/commit/a6505c63a7acb40371ea4958b7f0e1606d61b4ec.
