### ISSUE TITLE
Make the name and profile picture sharing the default and more visible

### ISSUE THREAD

**Issue by evonide** [google/vulncode-db#71]
The checkbox for sharing the profile picture and the full name is:

- Not activated by default.
- Barely visible.

We might want to change this to be on by default (opt-out) or at least make it way better visible on first sign-up/login.

**Comment by bluec0re** [comment]
We are now showing a flash message after the user logged in for the first time. Not super visible (a modal would be better maybe?) but it's a start.

**Comment by bluec0re** [comment]
We decided to keep the privacy settings as opt-out per default.
