### ISSUE TITLE
UI weirdness and smaller arbitrary issues

### ISSUE THREAD

**Issue by evonide** [google/vulncode-db#72]
- [ ] Review panel shows something like "User 4" instead of the name / email is this working as intended?
- [x] Date and vulnerability / CVE ID should not have line breaks (mostly in tables)!
- [x] Contributions in `profile/` page has an redundant sub-point without text.
- [x] Add a space between Issues and "?" in the top right navigation bar.
- [x] Don't show redundant column in `profile/` page if no picture URL is available.
- [x] `profile URL` should be renamed to `profile picture URL`?
- [x] A valid `profile URL` is required to change the name in the `profile/` route.
- [x] The footer should always be on the bottom never in the middle of a page. This can be seen for example in the `profile/` page.

**Comment by bluec0re** [comment]
> Review panel shows something like "User 4" instead of the name / email is this working as intended?
is WAI and related to #71
