### ISSUE TITLE
Replace the irritating continuous progress bar with a discrete steps timeline

### ISSUE THREAD

**Issue by evonide** [google/vulncode-db#73]
The progress bar which is visible when you view your proposals is irritating as it shows values like 12.5%, 25%, 50% etc..

We should replace this with something like a checkout process which has clear discrete steps.
I'm thinking of something like a timeline with circles that highlights how far the progress is.

**Comment by bluec0re** [comment]
Something like steppers in [vuetify](https://vuetifyjs.com/en/components/steppers/) or [angular material](https://material.angular.io/components/stepper/overview) could work better.

But we're probably too constrained by the size of the column. Using a full width row above the two cards should be better in this case.

**Comment by evonide** [comment]
I've used a simple Bootstrap stepper to resolve this :).
Fixed with https://github.com/google/vulncode-db/commit/1ae8e48aff538182810843cbe8939c86bd07d6b2.
