### ISSUE TITLE
Mark required fields in forms

### ISSUE THREAD

**Issue by bluec0re** [google/vulncode-db#78]
**Is your feature request related to a problem? Please describe.**
Forms currently do not indicate which fields are optional or required.

**Describe the solution you'd like**
Mark required or optional fields visually,

**Additional context**
WTForms adds a `required` css class to the fields which could be used for this.

**Comment by evonide** [comment]
Actually, we don't need this as leaving empty mandatory fields will bring up an indicator anyway.
I've added but commented out a red astersik for the CSS fields that are set to required in https://github.com/google/vulncode-db/commit/42f105ab45bc59d5b76203e7d5c346a12eff9539 though.

**Comment by bluec0re** [comment]
I'm still for having these as otherwise users will not know what is required and what not until they try to submit

**Comment by evonide** [comment]
Resolved with commit/efc2e5ef2670cc869a7c8cc37427eed14dc4a078.
